## docker-compose file that spins up a bytebot-desktop container
## and a postgres container. bytebot-ui and bytebot-agent are not included
## in this file, and can be run separately using npm, allowing for
## easier local development.

name: bytebot

services:
  bytebot-desktop:
    # Build from source
    build:
      context: ../packages/
      dockerfile: bytebotd/Dockerfile
    # Use pre-built image
    image: ghcr.io/bytebot-ai/bytebot-desktop:edge
    shm_size: "2g"
    container_name: bytebot-desktop
    restart: unless-stopped
    hostname: computer
    privileged: true
    ports:
      - "9990:9990" # bytebotd service & noVNC
    environment:
      - DISPLAY=:0
    networks:
      - bytebot-network

  # 使用外部MySQL数据库，不再需要本地PostgreSQL容器
  # MySQL连接信息: mysql://mysqlroot:Htjc2025a@8.137.123.168:3306/testData?charset=utf8mb4

networks:
  bytebot-network:
    driver: bridge

# 不再需要PostgreSQL数据卷
# volumes:
#   postgres_data:
