apiVersion: v2
name: postgresql
description: A Helm chart for PostgreSQL database
type: application
version: 0.1.0
appVersion: "16-alpine"
keywords:
  - postgresql
  - database
  - sql
maintainers:
  - name: Bytebot Team
sources:
  - https://github.com/bytebot-ai/bytebot