replicaCount: 1

image:
  repository: ghcr.io/bytebot-ai/bytebot-agent
  tag: edge
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9991
  targetPort: 9991
  annotations: {}

resources:
  limits:
    memory: "2Gi"
    cpu: "1000m"
  requests:
    memory: "1Gi"
    cpu: "500m"

nodeSelector: {}

tolerations: []

affinity: {}

env:
  DATABASE_URL: "mysql://mysqlroot:Htjc2025a@8.137.123.168:3306/testData?charset=utf8mb4"
  BYTEBOT_DESKTOP_BASE_URL: "http://bytebot-desktop:9990"
  BYTEBOT_LLM_PROXY_URL: ""
  # Legacy API key values for backward compatibility
  ANTHROPIC_API_KEY: ""
  OPENAI_API_KEY: ""
  GEMINI_API_KEY: ""

# New secret management structure
apiKeys:
  anthropic:
    useExisting: false
    secretName: ""
    secretKey: "anthropic-api-key"
    value: ""  # Only used if useExisting is false
  openai:
    useExisting: false
    secretName: ""
    secretKey: "openai-api-key"
    value: ""  # Only used if useExisting is false
  gemini:
    useExisting: false
    secretName: ""
    secretKey: "gemini-api-key"
    value: ""  # Only used if useExisting is false

config:
  databaseUrl: "mysql://mysqlroot:Htjc2025a@8.137.123.168:3306/testData?"
  bytebotDesktopUrl: "http://bytebot-desktop:9990"
  llmProxyUrl: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: bytebot-agent.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# 使用外部MySQL数据库，不再需要本地PostgreSQL
postgresql:
  enabled: false

externalDatabase:
  host: "8.137.123.168"
  port: 3306
  database: "testData"
  username: "mysqlroot"
  password: "Htjc2025a"
  existingSecret: ""
  existingSecretPasswordKey: ""