{{- $createSecret := false -}}
{{- if or .Values.env.ANTHROPIC_API_KEY .Values.env.OPENAI_API_KEY .Values.env.GEMINI_API_KEY -}}
  {{- $createSecret = true -}}
{{- else if and (not .Values.apiKeys.anthropic.useExisting) .Values.apiKeys.anthropic.value -}}
  {{- $createSecret = true -}}
{{- else if and (not .Values.apiKeys.openai.useExisting) .Values.apiKeys.openai.value -}}
  {{- $createSecret = true -}}
{{- else if and (not .Values.apiKeys.gemini.useExisting) .Values.apiKeys.gemini.value -}}
  {{- $createSecret = true -}}
{{- end -}}

{{- if $createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bytebot-agent.fullname" . }}-secrets
  labels:
    {{- include "bytebot-agent.labels" . | nindent 4 }}
type: Opaque
data:
  {{- /* Support legacy values for backward compatibility */ -}}
  {{- if .Values.env.ANTHROPIC_API_KEY }}
  anthropic-api-key: {{ .Values.env.ANTHROPIC_API_KEY | b64enc | quote }}
  {{- else if and (not .Values.apiKeys.anthropic.useExisting) .Values.apiKeys.anthropic.value }}
  anthropic-api-key: {{ .Values.apiKeys.anthropic.value | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.env.OPENAI_API_KEY }}
  openai-api-key: {{ .Values.env.OPENAI_API_KEY | b64enc | quote }}
  {{- else if and (not .Values.apiKeys.openai.useExisting) .Values.apiKeys.openai.value }}
  openai-api-key: {{ .Values.apiKeys.openai.value | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.env.GEMINI_API_KEY }}
  gemini-api-key: {{ .Values.env.GEMINI_API_KEY | b64enc | quote }}
  {{- else if and (not .Values.apiKeys.gemini.useExisting) .Values.apiKeys.gemini.value }}
  gemini-api-key: {{ .Values.apiKeys.gemini.value | b64enc | quote }}
  {{- end }}
{{- end }}